[package]
name = "OpenFlixServerRust"
version = "0.1.0"
authors = ["HinamoreCh4n <motherrussia711@gmail.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
rocket = { version = "*" }
rocket_codegen = "*"
diesel = { version = "*", features = ["sqlite"] }
dotenv = "*"
r2d2-diesel = "*"
r2d2 = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_json = { version = "*", features = ["preserve_order"] }
diesel_migrations = "*"
log = "*"

[dev-dependencies]
parking_lot = { version = "*", features = ["nightly"] }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "diesel_sqlite_pool"]
