[package]
name = "dim"
version = "0.3.0"
authors = ["Valerian G. <valerian.garleanu@pm.me>"]
edition = "2018"

[dependencies]
rocket = { version = "*" }
rocket_codegen = "*"
diesel = { version = "*", features = ["postgres"] }
dotenv = "*"
r2d2-diesel = "*"
r2d2 = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_json = { version = "*", features = ["preserve_order"] }
diesel_migrations = "*"
log = "*"
rocket_cors = "0.5.0"
lazy_static = "1.3.0"
dim-database = { path = "./src/database" }
dim-scanners = { path = "./src/scanners" }
dim-streamer = { path = "./src/streaming" }
walkdir = "2.2.9"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "diesel_postgres_pool"]

[dev-dependencies]
parking_lot = { version = "*", features = ["nightly"] }

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
