[package]
name = "OpenFlixServerRust"
version = "0.1.0"
authors = ["HinamoreCh4n <motherrussia711@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.0" }
rocket_codegen = "0.4.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.13.0"
r2d2-diesel = "1.0.0"
r2d2 = "0.8.3"
serde = { version = "1.0.89", features = ["derive"] }
serde_derive = "1.0.89"
serde_json = "1.0.39"
diesel_migrations = "1.4.0"
log = "0.4.6"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json", "diesel_sqlite_pool"]
